### PR TITLE
python3 fixes

### PR DESCRIPTION
**Pull request by EfthymisB**
Small python3 fixes when running `Archive.write_to_file`

### CODE REVIEW

**Comment by EfthymisB** [comment]
Small python3 fixes when running `Archive.write_to_file`

**Comment by rsgalloway** [comment]
HI, sorry for the delay, somehow this slipped through the cracks. These look like good changes. Have you signed the contributors agreement? https://github.com/alembic/alembic/wiki/Alembic-Contributor-License-Agreements

cc @lamiller0

**Comment by EfthymisB** [comment]
Hey, no worries at all.
I tried sending a signed copy to `contributors@alembic.io` as the document says, but looks like this address doesn't exist anymore. 

image

**Comment by lamiller0** [comment]
Please email it to:  miller.lucas+cla@gmail.com

Thanks!

**Comment by EfthymisB** [comment]
Done! Thanks @lamiller0

**Comment by lamiller0** [comment]
Got it, thanks!

**Pull request merged**
