### PR TITLE
Support for Python 2 and Python 3

### PR DESCRIPTION
**Pull request by PeterShinners**
No new dependencies or imports in the code.
This has a minimum requirement on Python 2.7 or Python 3.3+.

### CODE REVIEW

**Comment by rsgalloway** [comment]
Hi Peter! Thanks for your PR. Your changes LGTM. @lamiller0 any thoughts? 

In the meantime have you submitted a contributors agreement? You can find those [here](https://github.com/alembic/alembic/wiki/Alembic-Contributor-License-Agreements).

**Comment by lamiller0** [comment]
Pete is covered by an existing contributors agreement.

**Comment by lamiller0** [comment]
Changes LGTM as well.

**Comment by rsgalloway** [comment]
Merged and tagged as 1.2.0.

**Comment by PeterShinners** [comment]
I have a followup but wondered how best to proceed.
There are several functions that recurse the object/property hierarchy. They end up with a loop like
```
for child in obj.children.values():
    recurse(child)
```
Now that I'm using this more in the wild, I'm seeing errors like this
```
  File "cask.py", line 722, in close_tree
RuntimeError: dictionary changed size during iteration
```
This becomes an issue in Python 3 because `values()` returns a view and not an independent copy of a list. The easiest thing is wrap the call like `for child in list(obj.children.values())`. This has a possible performance loss on Python 2, because we are now making an extra list copy. My guess is this overhead is negligible and just go with the simple solution. An alternative would be a small function that does the most efficient thing on each version, which converts the loop into `for child in copyvalues(obj.children)`. Which would be best for cask?

There's four common methods that recurse like this. I'm only seeing the RuntimeError in the "close" calls. But there is also "save", "is_animated" and a "find". The others seem less likely to modify the objects while iterating. I do worry about "find" if there is code looking for objects and making changes (deleting or copying them?). How protective would you like to see the cask code? Just worry about the close? Should all of them be wrapped with a copy of the values?

I'll submit a followup with these changes. I just wasn't sure what your preferences might be. If there's no objection, I'll add that `copyvalues` function and convert all the recursion functions to use it?

**Pull request merged**
